run:
  go: "1.19"
  skip-dirs:
    - tmp

linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - revive
    - forbidigo
    - tagliatelle
    - misspell

linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # AllowList
