before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/dv

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    signature: '${artifact}.keyless.sig'
    certificate: '${artifact}.pem'
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'

brews:
  - tap:
      owner: knakayama
      name: homebrew-tap
    folder: Formula
    goarm: 7
    homepage:  https://github.com/knakayama/dv
    description: A command line tool to remove AWS default VPC(s)
    license: MIT
    test: |
      system "#{bin}/dv -v"
    dependencies:
      - name: go
        type: optional
    install: |
      bin.install "dv"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
