version: "3"

tasks:
  aws:setup:
    cmds:
      - ./scripts/install.sh

  aws:start:
    cmds:
      - localstack start -d
      - localstack wait

  aws:stop:
    cmds:
      - localstack stop

  aws:restart:
    cmds:
      - task: aws:stop
      - task: aws:start

  lint:
    cmds:
      - task: lint:ec
      - task: lint:golangci-lint
      - task: lint:gitleaks

  lint:ec:
    cmds:
      - editorconfig-checker

  lint:golangci-lint:
    cmds:
      - golangci-lint run

  lint:gitleaks:
    cmds:
      - gitleaks detect

  git:setup:
    cmds:
      - cp -pvf ./scripts/pre-commit.sh .git/hooks/pre-commit

  test:
    cmds:
      - go test -v -run {{.CLI_ARGS}} ./...
    env:
      AWS_ENDPOINT: "http://localhost:4566"
      DEFAULT_REGION: "ap-northeast-1"
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake

  test:all:
    cmds:
      - go test -v ./...
    env:
      AWS_ENDPOINT: "http://localhost:4566"
      DEFAULT_REGION: "ap-northeast-1"
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake

  test:vul:
    cmds:
      - govulncheck ./...

  build:
    cmds:
      - go build -v ./...

  mod:
    cmds:
      - go mod tidy
