version: "3"

tasks:
  aws:start:
    cmds:
      - localstack start -d
      - localstack wait

  aws:stop:
    cmds:
      - localstack stop

  aws:restart:
    cmds:
      - task: aws:stop
      - task: aws:start

  lint:
    cmds:
      - task: lint:ec
      - task: lint:golangci-lint
      - task: lint:gitleaks

  lint:ec:
    cmds:
      - ./tools/ec

  lint:golangci-lint:
    cmds:
      - ./tools/golangci-lint run

  lint:gitleaks:
    cmds:
      - ./tools/gitleaks detect

  lint:setup:
    cmds:
      - cp -pvf ./scripts/pre-commit.sh .git/hooks/pre-commit

  tool:install:
    cmds:
      - ./scripts/install.sh
