version: "3"

tasks:
  aws:start:
    cmds:
      - localstack start -d
      - localstack wait

  aws:stop:
    cmds:
      - localstack stop

  aws:restart:
    cmds:
      - task: aws:stop
      - task: aws:start

  lint:
    cmds:
      - task: lint:ec
      - task: lint:golangci-lint
      - task: lint:gitleaks

  lint:ec:
    cmds:
      - ec

  lint:golangci-lint:
    cmds:
      - golangci-lint run

  lint:gitleaks:
    cmds:
      - gitleaks detect

  lint:setup:
    cmds:
      - cp -pvf ./scripts/pre-commit.sh .git/hooks/pre-commit

  tool:install:
    cmds:
      - ./scripts/install.sh

  test:
    cmds:
      - go test -v -run {{.CLI_ARGS}} ./...
    env:
      AWS_ENDPOINT: "http://localhost:4566"
      DEFAULT_REGION: "ap-northeast-1"

  test:all:
    cmds:
      - go test -v ./...
    env:
      AWS_ENDPOINT: "http://localhost:4566"
      DEFAULT_REGION: "ap-northeast-1"
