name: test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: arduino/setup-task@v1
        with:
          version: "3.14.1"
      - run: |
          task mod
          task build
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install localstack
      - run: |
          task aws:start
          task test:vul:install
          task test:vul
          task test:all
